### ISSUE TITLE
Sceneform plugin v1.13.0 not working w/Android Studio 4 Canary 1

### ISSUE THREAD

**Issue by tellypresence** [google-ar/sceneform-android-sdk#912]
Android Studio 4 Canary 1, android gradle plugin 3.5.1
SceneForm plugin 1.13.0
Error typ. `Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)V`

Works perfectly on Android Studio 3.5.1

**Comment by danielawde9** [comment]
The issue still remain on android studio 3.6.1, working normal on 3.5.1

**Comment by VCDo** [comment]
Already mentioned here: https://github.com/google-ar/sceneform-android-sdk/issues/989.
Not working with Android Studio 3.6.0/3.6.1. But working with 3.5.3.

**Comment by danielawde9** [comment]
You can use [this](https://stackoverflow.com/questions/60468709/gradle-build-failed-with-new-import-rules) workaround till the issue is fixed

**Comment by sameerjj** [comment]
@danielawde9 thanks but that fix doesn't work for me currently.

**Comment by danielawde9** [comment]
@sameerjj did you follow the same step? it worked for me, 
Manually add the code, then android studio will automatically generate both sfa and sfb

**Comment by sameerjj** [comment]
@danielawde9 it might have to do with my project being a library not an application, but wasn't able to get it work. Ended up reverting to 3.5. Kind of embarrassing that these guys are putting out releases with such glaring issues. Probably won't update for the foreseeable future can't risk having issues when I need to focus on development
